version: "3"
services:
  db:
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - ./.docker/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  db_test:
    image: postgres:alpine
    env_file:
      - .env.test
    ports:
      - 5433:5432
