version: "3"
services:
  db:
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - ./.docker/db:/var/lib/postgresql/data
    ports:
      - 9999:5432
  db-test:
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - 9998:5432
